### ISSUE TITLE
broadsea-atlasdb possible vulnerability to kinsing/kdevtmpfsi cryptomining malware

### ISSUE THREAD

**Issue by sudoshi** [OHDSI/Broadsea#73]
This weekend we were informed by Google Cloud that our Broadsea VM was compromised by a malware.

https://www.bigbinary.com/blog/how-my-server-got-infected-with-a-crypto-mining-malware-and-how-i-fixed-it

Apparently some misconfigured postgres container images are vulnerable to this exploit.

I was able to replicate the problem on our development VM running locally.  We followed the procedures to remove and repeated them on our GCP VM.  Both Ubuntu 22.xx

This included installing clamav and rkhunter and running full scans with remove instructions for any found malware.

We should probably update/upgrade the container in Broadsea 3.0 to one running pg-12 or even pg-14 with the vulnerability addressed.

https://www.bleepingcomputer.com/news/security/microsoft-kubernetes-clusters-hacked-in-malware-campaign-via-postgresql/

**Comment by leeevans** [comment]
I have updated the github broadsea-atlasdb Dockerfile to use postgres:15.2-alpine and pushed ohdsi/broadsea-atlasdb:latest and ohdsi/broadsea-atlasdb:2.0.0 to Docker Hub replacing the original images.

@sudoshi can you please try testing out broadsea with this new broadsea-atlasdb image?

Note. You may need to "docker volume rm atlasdb-postgres-data" because the old docker volume is not compatible with postgres 15.2 - make sure there is no data in that docker volume that you want to keep before you remove it

**Comment by sudoshi** [comment]
I believe the problem has been eliminated as a result of the upgrade to postgres:15.2-alpine.  I deleted all previous layers and rebuilt the local container from your new images.

Thank you!  We can close this issue.
![Screenshot 2023-04-26 at 10 29 41 AM](https://user-images.githubusercontent.com/100962480/234992711-d5c3f1f5-029b-4d51-87f9-67658af6fb36.png)

**Comment by leeevans** [comment]
Thanks @sudoshi I appreciate you taking the time to test this!

I will close the issue now.
